### ISSUE TITLE
AttributeError: module 'autograd.numpy' has no attribute 'numpy_extra'

### ISSUE THREAD

**Issue by muszyna25** [HIPS/autograd#610]
Hi, I am currently working on a code (Python 2.7) that was written about 5 years ago. The code uses Autograd and it looks like that module `'autograd.numpy'` has no attribute `'numpy_extra'`. This is an error that I am getting: `AttributeError: module 'autograd.numpy' has no attribute 'numpy_extra'`.

Here is the snippet of the code where this error comes from:
`if type(self.DIVERSITY) is autograd.numpy.numpy_extra.ArrayNode:
            self.DIVERSITY = self.DIVERSITY.value[0,0]`

Would you be able to advise how this `autograd.numpy.numpy_extra.ArrayNode` was replaced/changed in the latest release of the Autograd, please? 

Thank you!
